Mod Log implementation
JojoFR1/Joseta pull request #4
Opened 2024-12-15 14:42 UTC by JojoFR1

Mod Log impletation PR

2025-01-25 17:43 UTC, ZetaMap reviewed
plutot bien, ça manque de print dans la console ou tu logging des actions effectuées, dans un salon définie. après pour l'instant, j'ai pas une vue d'ensemble, mais c'est bien pour l'instant.

2025-01-25 17:43 UTC, ZetaMap commented on src/joseta/JosetaBot.java
> +            if (sanction.getSanctionTypeId() == 40) {
Si c'est un type de sanction, utilise la constante associée plutôt que la valeur directement, si tu peux bien sûr.

2025-01-25 17:43 UTC, ZetaMap commented on src/joseta/commands/ModCommand.java
> +    protected static final ModLog modLog = ModLog.getInstance();
le principe de "instance()" c'est que c'est la classe elle-même qui stocke l'instance une fois, puis qui renvoie juste la variable privée, justement pour éviter de la stocker quand tu fais instance(), puis ensuite t'a juste à faire classe.instance().

2025-01-25 17:49 UTC, JojoFR1 commented on src/joseta/commands/ModCommand.java
> +    protected static final ModLog modLog = ModLog.getInstance();
Ah ducoup faut pas la stocker? C'était pour éviter la répétition vu que je crois que c'est pas mal utilisé

2025-01-25 17:51 UTC, JojoFR1 commented
> ça manque de print dans la console

C'est vrai, quel genre de print ? Juste quand une commande est effectuée ou autre ?
Je le ferai en même temps que j'améliore les réponses 

> tu logging des actions effectuées, dans un salon définie. 

Ça le système de log je prévois de le faire (je crois je l'ai mis dans le README dans la section `Plans` mais je suis pas sûr)

2025-01-26 07:21 UTC, xorblo-doitus requested changes

2025-01-26 07:21 UTC, Patou-todoG commented on README.md
> +We had the choices between JavaScript, Python or Java. Due to personnal preferences, we chose Java and JDA was a library we already had experience in.
```suggestion
We could have used JavaScript or Python. But due to personal preferences, we have chosen Java and JDA, as it was a library we already had experience with.
```

2025-01-26 07:21 UTC, Patou-todoG commented on README.md
> +      - A `/modlog` command to acces a member moderation history.
Ce serait sûrement mieux sous la forme d'un tableau.
Tu peux utiliser ce site pour en créer un facilement : https://www.tablesgenerator.com/markdown_tables

2025-01-26 07:21 UTC, Patou-todoG commented on README.md
> +- Multiple features:
```suggestion
```
On le sait déjà que ce sont des fonctionnalités, c'est écrit dans le titre et l'introduction de la liste.

2025-01-26 07:21 UTC, xorblo-doitus commented on README.md
> +  - A **Leave Message** for quitting members (not *yet* configurable)
```suggestion
  - A **Goodbye Message** for leaving members (not *yet* configurable)
```
"Leave message" peut vouloir dire "laisser un message", autant éviter les ambigüités.

2025-01-26 07:21 UTC, xorblo-doitus commented on README.md
> +  - An **Auto Response** for a common question (not *yet* configurable)
```suggestion
  - An **Auto Response** for common questions (not *yet* configurable)
```
Je sais que pour l'instant ça ne fait que pour une question, mais je trouve que la formulation au singulier fait bizarre.

2025-01-26 07:21 UTC, xorblo-doitus commented on README.md
> +  - Better message response (sucess & failed)
```suggestion
  - Better message responses (sucess & failure)
```

2025-01-26 07:21 UTC, xorblo-doitus commented on README.md
> +  - Allow to change *some* variable without having to rebuild and restart
```suggestion
  - Allow to change *some* variables without having to rebuild and restart
```

2025-01-26 07:21 UTC, xorblo-doitus commented on README.md
> +  - Allow to be Runnable outside of our server
```suggestion
  - Allow to be runnable outside of our server
```

2025-01-26 07:21 UTC, xorblo-doitus commented on README.md
> +You will need at the minimum **JDK 17** or later to be able to build this project.
```suggestion
Building requires **JDK 17** or later.
```
The shorter, the better.

2025-01-26 07:21 UTC, xorblo-doitus commented on README.md
> +You will first need to follow the instruction in the `secret_template.cfg` file before being able to run the bot.
```suggestion
You will first need to follow the instructions in the `secret_template.cfg` file before being able to run the bot.
```

2025-01-26 18:38 UTC, ZetaMap commented on src/joseta/commands/ModCommand.java
> +    protected static final ModLog modLog = ModLog.getInstance();
dans ce cas tu peut rendre les méthodes de la classe statiques. comme sa plus de problème sur l'instance

2025-01-27 12:06 UTC, JojoFR1 commented on README.md
> +      - A `/modlog` command to acces a member moderation history.
Peut-être je vais essayer

2025-01-27 14:49 UTC, JojoFR1 commented on README.md
> +      - A `/modlog` command to acces a member moderation history.
Ça va être push

2025-01-27 15:11 UTC, xorblo-doitus requested changes

2025-01-27 15:11 UTC, xorblo-doitus commented on README.md
> +This bot is multipurpose and isn't centered around one thing, any feature added (removed or changed) are based off our needs. Here's a list of all the features this bot has:
```suggestion
This bot is multipurpose and isn't centered around one thing, any features added (removed or changed) are based on our needs. Here's a list of all the features this bot has:
```

2025-01-27 15:11 UTC, xorblo-doitus commented on README.md
> +- | Commands    | Use                                |
```suggestion
- Multiple commands:
| Commands    | Use                                |
```
ça fait bizarre d'avoir un point devant le tableau.

2025-01-27 15:30 UTC, xorblo-doitus approved these changes
Les changements au README sont OK.

2025-01-31 17:48 UTC, JojoFR1 commented
Tout devrait être bon, un dernier check ?

2025-02-03 20:43 UTC, merged